//
//  main.swift
//  configen
//
//  Created by Suyash Srijan on 26/10/2018.
//  Copyright © 2018 The App Business. All rights reserved.
//

import Foundation
import SwiftSyntax

// Create the command line parser
let parser = CommandLineParser()

// Get the app name from the first command line argument
let appName = NSString(string: CommandLine.arguments.first ?? "configen").lastPathComponent

// Get the output struct name from the command line parser
let structName = parser.outputStructName

// Create a comment object
let comment = Comment(appName: appName)

// Create a SyntextTreeParser to parse the input Swift file and insert a auto-generated comment statement at the top of the parsed tree
let sourceFile = try SyntaxTreeParser.parse(URL(string: parser.inputSwiftFilePath)!).statements.inserting(comment.autoGeneratedComment(), at: 0)

// Rewrite the input Swift file
let newFile = FileRewriter(structName: structName).visit(sourceFile)

// Create a path to the file to which the output Swift file contents will be written to
let writePath = URL(fileURLWithPath: parser.outputStructDirectory).appendingPathComponent("\(structName).swift")

// Write the output Swift file and throw an error if it fails
do {
  try newFile.description.write(to: writePath, atomically: true, encoding: .utf8)
} catch let err {
  fatalError("There was an error when writing to the file at location: \(writePath.absoluteString)/. The full error is: \(err.localizedDescription)")
}
