// auto-generated by configen
// to add or remove properties, edit the mapping file: '/Users/johnsanderson/Documents/ConfigGenerator/ConfigenDemo/AppEnvironment.map'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md

import Foundation

class AppEnvironment {

  let entryPointURL: URL = URL(string: "http://example.com/production")!

  let enableFileSharing: Bool = true

  let analyticsKey: String = "haf6d9fha8v56abs"

  let environment: Environment = .Production

  let adUnitPrefix: String = "production_ad_unit"

  let retryCount: Int = 4

}

