// auto-generated by configen
// to add or remove properties, edit the mapping file: '/Users/johnsanderson/Documents/ConfigGenerator/ConfigenDemo/AppEnvironment.map'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md

import Foundation

class AppEnvironment {

  let myConfigBool: Bool = false

  let myConfigUrl: URL = URL(string: "http://example.com/production")!

  let myConfigInt: Int = 10

  let myConfigString: String = "Hello! From TAB prod file"

}

