//
//  FileRewriter.swift
//  configen
//
//  Created by Suyash Srijan on 26/10/2018.
//  Copyright © 2018 The App Business. All rights reserved.
//

import Foundation
import SwiftSyntax

/// This class is responsible for taking an input configuration Swift file and "rewriting" the struct.
///
/// The output configuration file is generated by simply renaming the input struct and removing the configuration protocol conformance clause. This results
class FileRewriter: SyntaxRewriter {
  
  // MARK: - Properties -
  // MARK: Private
  
  /// The name of the struct
  private let name: String
  
  // MARK: - Init -
  // MARK: Public
  
  /// Class initializer
  ///
  /// - Parameter structName: The struct name that will be used to rename the input struct
  init(structName: String) {
    self.name = structName
  }
  
  // MARK: - Functions -
  // MARK: Public
  
  /// Visit a `StructDeclSyntax` node in the AST
  ///
  /// - Parameter node: A `StructDeclSyntax` node
  /// - Returns: A `DeclSyntax` node
  override func visit(_ node: StructDeclSyntax) -> DeclSyntax {
    let newIdentifier = node.identifier.withKind(.identifier(name)).withTrailingTrivia(.spaces(1))
    return node.withIdentifier(newIdentifier).withInheritanceClause(nil)
  }
}
